# Generated by Django 5.1.3 on 2024-11-28 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='superhero',
            name='power',
            field=models.JSONField(),
        ),
    ]
