# Generated by Django 5.1.3 on 2024-11-28 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0002_alter_superhero_power'),
    ]

    operations = [
        migrations.AlterField(
            model_name='superhero',
            name='debut_date',
            field=models.TextField(),
        ),
    ]
