# Generated by Django 5.1.3 on 2024-11-28 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0003_alter_superhero_debut_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='superhero',
            name='power',
            field=models.TextField(),
        ),
    ]
