# Generated by Django 5.1.3 on 2024-11-29 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0004_alter_superhero_power'),
    ]

    operations = [
        migrations.AddField(
            model_name='superhero',
            name='is_marvel',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='superhero',
            name='is_villain',
            field=models.BooleanField(default=False),
        ),
    ]
