# Generated by Django 5.1.3 on 2024-12-01 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0005_superhero_is_marvel_superhero_is_villain'),
    ]

    operations = [
        migrations.AddField(
            model_name='superhero',
            name='alias',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='superhero',
            name='teams',
            field=models.TextField(default=''),
        ),
    ]
